function graph_plot_motion(X, I, labelON)
% plot positions of the agents to see if the dynamics is correct
% Input:
%   time - adaptive time instances generated by solver ode113
%   x    - trajectory data; size = time x (d x N)
% By Fei Lu

I.t0 = 0;
I.tgrid = I.t0:I.dt:I.t0 + I.dt * I.L;
tgrid = I.tgrid;
[N, ~, L] = size(X);
labels = string(1:N);


figure('Color', 'white');

x1 = squeeze(X(:, 1, :));
x2 = squeeze(X(:, 2, :));

x1_lo = min(min(squeeze(X(:, 1, :))));
x1_up = max(max(squeeze(X(:, 1, :))));
x2_lo = min(min(squeeze(X(:, 2, :))));
x2_up = max(max(squeeze(X(:, 2, :))));

s_seq = 1:max(floor(L/50),1):L;

filename = 'particles.gif';

for i = 1:length(s_seq)
    s = s_seq(i);
    plot(x1(:, s), x2(:, s), 'o');
    axis([x1_lo, x1_up, x2_lo, x2_up]);
    
    if labelON
        text(x1(:, s), x2(:, s),labels,'VerticalAlignment','bottom','HorizontalAlignment','right')
    end
    titleT = strcat('True: time ', num2str(tgrid(s), '%.3f'));   title(titleT);

    drawnow
    frame = getframe(gcf);
    im = frame2im(frame);
    [imind,cm] = rgb2ind(im,256);
    
    if s == 1
        imwrite(imind,cm,filename,'gif', 'Loopcount',inf);
    else
        imwrite(imind,cm,filename,'gif','WriteMode','append', 'DelayTime', 0);
    end
    
end




return