function graph_plot_motion_kuramoto(X, I, labelON)
% plot positions of the agents to see if the dynamics is correct
% Input:
%   time - adaptive time instances generated by solver ode113
%   x    - trajectory data; size = time x (d x N)
% By Fei Lu, Quanjun Lang

% I.tgrid =0:I.dt:(I.dt * I.steps);

%X = X(:,:,1:100);                                                                                                              % To display a shorter path

[N, ~, L] = size(X);
tgrid = I.tgrid(1:L);
labels = string(1:N);

all_class = {[6, 7, 9], [2, 4, 5], [1, 3, 8, 10]};
class_ind = [3, 2, 3, 2, 2, 1, 1, 3, 1, 3];
color_order = {[0    0.4470    0.7410], [0.8500    0.3250    0.0980], [0.9290    0.6940    0.1250]};

figure('Color', 'white');

X_1d = X;
[N, ~, TN] = size(X);

X = zeros(N, 2, TN);
X(:, 1, :) = cos(X_1d);
X(:, 2, :) = sin(X_1d);


x1 = squeeze(X(:, 1, :));
x2 = squeeze(X(:, 2, :));

x1_lo = min(min(squeeze(X(:, 1, :))));
x1_up = max(max(squeeze(X(:, 1, :))));
x2_lo = min(min(squeeze(X(:, 2, :))));
x2_up = max(max(squeeze(X(:, 2, :))));

s_seq = 1:max(floor(L/200),1):L;

% h = figure;
gif('kuramoto.gif')
set(gcf, "Position", [500, 500, 400, 400])
xx = linspace(-1, 1, 100);
y1 = sqrt(1 - xx.^2);
y2 = -y1;


for i = 1:length(s_seq)
    s = s_seq(i);
    
    hold on
    plot(xx, y1, 'color', 'k');
    plot(xx, y2, 'color', 'k');
    for k = 1:N
        plot(x1(k, s), x2(k, s), 'o', 'LineWidth', 2, 'MarkerSize', 5, 'Color', color_order{class_ind(k)});
        if labelON
            text(x1(k, s), x2(k, s), labels(k), 'VerticalAlignment','bottom','HorizontalAlignment','right', 'FontSize', 20, 'Color', color_order{class_ind(k)})
        end

    end

    axis([x1_lo, x1_up, x2_lo, x2_up]);
    titleT = strcat('True: time ', num2str(tgrid(s), '%.3f'));   title(titleT);
    % pause(0.001)
    gif
    clf
end

close gcf
% close gcf
% filename = 'particles.gif';
%
% for i = 1:length(s_seq)
%     hold on
%     s = s_seq(i);
%     for k = 1:N
%         plot(x1(k, s), x2(k, s), 'o', 'LineWidth', 5, 'MarkerSize', 5, 'Color', color_order{class_ind(k)});
%         if labelON
%             text(x1(k, s), x2(k, s), labels(k), 'VerticalAlignment','bottom','HorizontalAlignment','right', 'FontSize', 20, 'Color', color_order{class_ind(k)})
%         end
%     end
%     axis([x1_lo, x1_up, x2_lo, x2_up]);
%     titleT = strcat('True: time ', num2str(tgrid(s), '%.3f'));   title(titleT);
%     pause(0.001)
%     drawnow
%     frame = getframe(gcf);
%     im = frame2im(frame);
%     [imind,cm] = rgb2ind(im,256);
%
%
%     if s == 1
%         imwrite(imind,cm,filename,'gif', 'Loopcount',inf);
%     else
%         imwrite(imind,cm,filename,'gif','WriteMode','append', 'DelayTime', 0);
%     end
%
% end




return